[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

lib_ldf_mode = deep+

build_flags =
    -DMQTT_MAX_PACKET_SIZE=1024

lib_deps =
    knolleary/PubSubClient@^2.8
    emelianov/modbus-esp8266@^4.1.0